2018/05/25 14:38:50 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "10.39.30.76"
2018/05/25 14:38:50 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "10.39.30.76", referrer: "http://10.39.30.76/test"
2018/05/25 14:39:14 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "10.39.30.76"
2018/05/25 14:39:14 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "10.39.30.76", referrer: "http://10.39.30.76/test"
2018/05/25 14:39:14 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "10.39.30.76"
2018/05/25 14:39:15 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "10.39.30.76", referrer: "http://10.39.30.76/test"
2018/05/25 14:39:16 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "10.39.30.76"
2018/05/25 14:39:16 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "10.39.30.76", referrer: "http://10.39.30.76/test"
2018/05/25 14:39:17 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "10.39.30.76"
2018/05/25 14:39:17 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "10.39.30.76", referrer: "http://10.39.30.76/test"
2018/05/25 14:45:13 [error] 7#7: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "m.homework.test"
2018/05/25 14:45:13 [error] 7#7: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "m.homework.test", referrer: "http://m.homework.test/test"
2018/05/25 14:48:35 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "m.homework.test"
2018/05/25 14:48:35 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "m.homework.test", referrer: "http://m.homework.test/test"
2018/05/25 14:48:38 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /test HTTP/1.1", upstream: "http://172.18.0.4:8080/test", host: "m.homework.test"
2018/05/25 14:48:38 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: l.blog.server, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8080/favicon.ico", host: "m.homework.test", referrer: "http://m.homework.test/test"
2018/05/25 14:48:49 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug could not open the remote debug file '/var/log/xdebug.log'" while reading response header from upstream, client: 172.18.0.1, server: 10.39.30.76, request: "GET /test HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "10.39.30.76"
2018/05/25 14:49:17 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug could not open the remote debug file '/var/log/xdebug.log'" while reading response header from upstream, client: 172.18.0.1, server: 10.39.30.76, request: "GET /test HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "10.39.30.76"
2018/05/25 14:50:09 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug could not open the remote debug file '/var/log/xdebug.log'" while reading response header from upstream, client: 172.18.0.1, server: 10.39.30.76, request: "GET /test HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "10.39.30.76"
2018/05/25 14:52:44 [error] 7#7: *19 FastCGI sent in stderr: "PHP message: Xdebug could not open the remote debug file '/var/log/xdebug.log'" while reading response header from upstream, client: 172.18.0.1, server: 10.39.30.76, request: "GET /test HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "10.39.30.76"
2018/05/25 16:22:58 [error] 7#7: *1 FastCGI sent in stderr: "PHP message: Xdebug could not open the remote debug file '/var/log/xdebug.log'" while reading response header from upstream, client: 172.18.0.1, server: 10.39.30.76, request: "GET /test HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "10.39.30.76"
